library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
library(tidyverse)
library(lubridate)
library(sf)
library(tigris)
library(mapview)
library(leaflet)

df = read.csv('testing.csv') %>% filter(Defining.Parameter == 'PM2.5' | Defining.Parameter == 'Ozone')
df$Date = as.POSIXct(df$Date)
statecity = df %>% select(state_name, state_id, city_ascii, lat, lng) %>% distinct()
